config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  root 'tweets#index'
  get 'search_user', to: 'users#search_user'
  post 'search_user', to: 'users#search_user'
  get '/:username', to: 'users#show', as: :user

  scope ':username' do
    resource :following, only: [:show]
    resource :followers, only: [:show]
  end

  resources :tweets, except: [:new]
  resources :relationships, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followee, class_name: "User"

  validates :follower_id, presence: true
  validates :followee_id, presence: true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :tweet, presence: true, length: {minimum: 1, maximum: 280}, allow_blank: false
  belongs_to :user, counter_cache: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  before_save :sanitize_inputs
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followee_id", dependent: :destroy

  has_many :following, through: :active_relationships, source: :followee, dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower, dependent: :destroy

  validates :name, presence: true
  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true

  def follow(user)
    active_relationships.create(followee_id: user.id)
  end

  def unfollow(followee_user)
    active_relationships.find_by(followee_id: followee_user.id).destroy
  end

  def following?(user)
    following.include?(user)
  end

  def sanitize_inputs
    self.email = email.downcase
    self.username = username.downcase
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protected

  def after_sign_in_path_for(resource)
    user_path(current_user.username)
  end
end

app/controllers/concerns/user_scoped.rb
module UserScoped
  extend ActiveSupport::Concern
  included do
    before_action :set_user
  end

  def set_user
    @user = User.find_by(username: params[:username])
  end
end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController
  include UserScoped

  def show
    @user_followers = @user.followers.order("username ASC").paginate(page: params[:page], per_page: 10)
  end
end

app/controllers/followings_controller.rb
class FollowingsController < ApplicationController
  include UserScoped

  def show
    @user_following = @user.following.order("name ASC").paginate(page: params[:page], per_page: 10)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
  end

  def acount_update_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    user = User.find(params[:followee_id])
    current_user.follow(user)
    redirect_to root_path
  end

  def destroy
    user = Relationship.find(params[:id]).followee
    current_user.unfollow(user)
    redirect_to root_path
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[index show]

  # GET /tweets or /tweets.json
  def index
    @tweets = Tweet.includes(:user).all.order("created_at DESC").paginate(page: params[:page], per_page: 10)
    @tweet = Tweet.new
    @users = User.all.order('name ASC')
  end

  # GET /tweets/1 or /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = current_user.tweets.build
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets or /tweets.json
  def create
    @tweet = current_user.tweets.build(tweet_params)
    if @tweet.save
      flash[:notice] = "Tweet was successfully created."
      redirect_to root_path
    else
      flash[:alert] = "Tweet can not be blank."
      redirect_to root_path
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: "Tweet was successfully updated." }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: "Tweet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_tweet
    @tweet = Tweet.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def tweet_params
    params.require(:tweet).permit(:tweet)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include UserScoped

  def show
    @tweets = @user.tweets.order("created_at DESC").paginate(page: params[:page], per_page: 10)
  end

  def search_user
    return redirect_to root_path if params[:followee].blank?
    @to_follow = User.find_by(username: params[:followee])
    return redirect_to root_path, alert: "Username does not exists." if !@to_follow
    return redirect_to root_path, alert: "Invalid operation." if @to_follow == current_user

    return redirect_to root_path, alert: "User already followed." if current_user.following.include?(@to_follow)

    follow = Relationship.create(follower: current_user, followee: @to_follow)
    redirect_to user_path(@to_follow.username), notice: "Now, your are following #{@to_follow.username}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/followers/show.html.erb
<% @user_followers.each do |follower| %>
  <div class="columns is-mobile is-centered mt-5">
    <div class="column is-half">
      <div class="box">
        <div class="panel-block">
          <article class="media">
            <div class="media-left">
              <figure class="image is-32x32">
                <img src="https://bulma.io/images/placeholders/32x32.png">
              </figure>
            </div>
            <div class="media-content">
              <div class="content">
                <p>
                  <strong><%= link_to follower.name, user_path(follower.username) %></strong>
                  <small>@<%= follower.username %></small>
                </p>
                <% if current_user %>
                  <%= render 'components/follow_btn', user: follower %>
                <% end %>
              </div>
            </div>
          </article>
        </div>
      </div>
    </div>
  </div>
<% end %>

<%= render 'components/pagination', obj: @user_followers %>

<%= link_to 'Back', root_path, class: "button is-info ml-5 mt-5" %>

app/views/followings/show.html.erb
<% @user_following.each do |user| %>
  <div class="columns is-mobile is-centered mt-5">
    <div class="column is-half">
      <div class="box">
        <div class="panel-block">
          <article class="media">
            <div class="media-left">
              <figure class="image is-32x32">
                <img src="https://bulma.io/images/placeholders/32x32.png">
              </figure>
            </div>
            <div class="media-content">
              <div class="content">
                <p>
                  <strong><%= link_to user.name, user_path(user.username) %></strong>
                  <small>@<%= user.username %></small>
                </p>
                <% if current_user %>
                  <%= render 'components/follow_btn', user: user %>
                <% end %>
              </div>
            </div>
          </article>
        </div>
      </div>
    </div>
  </div>
<% end %>

<%= render 'components/pagination', obj: @user_following %>

<%= link_to 'Back', root_path, class: "button is-info ml-5 mt-5" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterClone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/flash' %>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class="notification is-primary global-notification">
    <button class="delete"></button>
    <p class="notice"><%= notice %></p>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="notification is-danger global-notification">
    <button class="delete"></button>
    <p class="notice"><%= alert %></p>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar is-info">
  <div class="navbar-brand">
    <%= link_to root_path, class: "navbar-item" do %>
      <h1 class="title is-5">Twitter</h1>
    <% end %>
    <div class="navbar-burger burger" data-target="navbarExample">
      <span></span>
      <span></span>
      <span></span>
    </div>
  </div>

  <div id="navbarExample" class="navbar-menu">
    <div class="navbar-end">
      <div class="navbar-item">
        <div class="field is-grouped">
          <% if user_signed_in? %>
            <p class="control">
              <%= link_to 'Twittear', root_path, class: "button is-info is-inverted" %>
            </p>
            <p class="control">
              <%= link_to "@" + current_user.username, user_path(current_user.username), class: "button is-info" %>
            </p>
            <p class="control">
              <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "button is-info" %>
            </p>
          <% else %>
            <p class="control">
              <%= link_to "Sign In", new_user_session_path, class: "button is-info" %>
            </p>
            <p class="control">
              <%= link_to "Sign Up", new_user_registration_path, class: "button is-info" %>
            </p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/tweets/_feed.html.erb
<div class="column is-half">
  <% if user_signed_in? %>
    <article class="media box">
      <figure class="media-left">
        <p class="image is-64x64">
          <%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.name) %>
        </p>
      </figure>
      <div class="media-content">
        <%= render 'tweets/form' %>
      </div>
    </article>
  <% end %>

  <% @tweets.each do |tweet| %>
    <div class="box">
      <article class="media">
        <div class="media-left">
          <figure class="image is-64x64">
            <%= gravatar_image_tag(tweet.user.email, size: 64, alt: tweet.user.name) %>
          </figure>
        </div>
        <div class="media-content">
          <div class="content">
            <strong><%= tweet.user.name %></strong>
            <small>@<%= tweet.user.username %></small> -
            <small class="is-size-7"><%= tweet.created_at %></small>
            <p> <%= tweet.tweet %> </p>
          </div>
          <% if user_signed_in? %>
          <nav class="level">
            <div class="level-left is-mobile">
              <%= link_to tweet, class: "level-item" do %>
                <span class="icon"> <i class="fa fa-link" aria-hidden="true"></i> </span>
              <% end %>
              <%= link_to edit_tweet_path(tweet), class: "level-item" do %>
                <span class="icon"> <i class="fa fa-pencil" aria-hidden="true"></i> </span>
              <% end %>
              <%= link_to tweet, method: :delete, data: { confirm: "Are you sure?" } do %>
                <span class="icon"> <i class="fa fa-trash-o" aria-hidden></i> </span>
              <% end %>
            </div>
          </nav>
        <% end %>
        </div>
      </article>
    </div>
  <% end %>
</div>

app/views/tweets/_form.html.erb
<%= simple_form_for(@tweet) do |f| %>
  <div class="field">
    <div class="control">
      <%= f.input :tweet, label: "Tweet about it", input_html: { class: "textarea" }, wrapper: false, label_html: { class: "label" }, placeholder: "What's happening?", autofocus: true %>
    </div>
  </div>
  <%= f.button :submit, class: "button is-info" %>
<% end %>

app/views/tweets/_profile.html.erb
<div class="column is-one-quarter">
  <nav class="panel">
    <p class="panel-heading">Profile</p>
    <div class="panel-block">
      <article class="media">
        <div class="media-left">
          <figure class="image is-64x64">
            <%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.name) %>
          </figure>
        </div>
        <div class="media-content">
          <div class="content">
            <p>
              <strong><%= current_user.name %></strong> <br>
              <small>@<%= current_user.username %></small>
            </p>
          </div>
        </div>
      </article>
    </div>
    <div class="panel-block">
      <div class="level is-mobile">
        <div class="level-item has-centered-text">
          <div>
            <p class="heading">Tweets</p>
            <p class="title is-6"><%= current_user.tweets.count %></p>
          </div>
        </div>
        <div class="level-item has-centered-text">
          <div>
            <p class="heading">Followers</p>
            <p class="title is-6">0</p>
          </div>
        </div>
        <div class="level-item has-centered-text">
          <div>
            <p class="heading">Following</p>
            <p class="title is-6">0</p>
          </div>
        </div>
      </div>
    </div>
  </nav>
</div>

app/views/tweets/edit.html.erb
<div class="section">
	<div class="container">
		<div class="columns is-centered">
			<div class="column is-half">
				<h1 class="title">Editing Tweet</h1>
				<%= render 'form', tweet: @tweet %>
			</div>
		</div>
	</div>
</div>

<nav class="navbar is-fixed-bottom">
	<div class="navbar-menu">
		<div class="navbar-item">
			<div class="field is-grouped">
				<p class="control">
					<%= link_to 'Cancel', root_path, class: "button is-dark" %>
				</p>
		</div>
	</div>
</nav>

app/views/tweets/index.html.erb
<section class="section">
  <div class="container">
    <div class="columns">
      <% if user_signed_in? %>
        <%= render 'components/profile' %>
      <% end %>
      <%= render 'components/feed' %>
      <%= render 'components/follow_feed' %>
    </div>
  </div>
</section>

app/views/tweets/show.html.erb
<div class="columns is-mobile is-centered mt-5">
  <div class="column is-half">
    <div class="box">
      <article class="media">
        <div class="media-left">
          <figure class="image is-64x64">
            <%= gravatar_image_tag(@tweet.user.email, size: 64, alt: @tweet.user.name) %>
          </figure>
        </div>
        <div class="media-content">
          <div class="content">
            <strong><%= @tweet.user.name %></strong>
            <small>@<%= @tweet.user.username %></small> -
            <small class="is-size-7"><%= @tweet.created_at.getlocal.strftime("%d %b %y, %H:%M%p") %></small>
            <p> <%= @tweet.tweet %> </p>
          </div>
          <% if user_signed_in? %>
          <nav class="level">
            <div class="level-left is-mobile">
              <%= link_to @tweet, class: "level-item" do %>
                <span class="icon"> <i class="fa fa-link" aria-hidden="true"></i> </span>
              <% end %>
              <%= link_to @tweet, method: :delete, data: { confirm: "Are you sure?" } do %>
                <span class="icon"> <i class="fa fa-trash-o" aria-hidden></i> </span>
              <% end %>
            </div>
          </nav>
        <% end %>
        </div>
      </article>
    </div>
  </div>
</div>

<%= link_to 'Back', root_path, class: "button is-info ml-5" %>

app/views/users/_search.html.erb
<% if user_signed_in? %>
  <%= form_with(url: search_user_path, local: true) do |f| %>
    <nav class="panel">
      <p class="panel-heading">Search user</p>
      <div class="panel-block">
        <div class="mr-1">
          <%= f.text_field :followee, class: "input", type: "text", placeholder: "Search user to follow", required: true %>
        </div>
        <div class="ml-1">
          <%= f.submit "Follow", class: "button is-info" %>
        </div>
      </div>
    </nav>
  <% end %>
<% end %>

app/views/users/followers.html.erb
<% @user_followers.each do |follower| %>
  <div class="columns is-mobile is-centered mt-5">
    <div class="column is-half">
      <div class="box">
        <div class="panel-block">
          <article class="media">
            <div class="media-left">
              <figure class="image is-32x32">
                <img src="https://bulma.io/images/placeholders/32x32.png">
              </figure>
            </div>
            <div class="media-content">
              <div class="content">
                <p>
                  <strong><%= link_to follower.name, user_path(follower.username) %></strong>
                  <small>@<%= follower.username %></small>
                </p>
                <% if current_user %>
                  <%= render 'components/follow_btn', user: follower %>
                <% end %>
              </div>
            </div>
          </article>
        </div>
      </div>
    </div>
  </div>
<% end %>

<%= render 'components/pagination', obj: @user_followers %>

<%= link_to 'Back', tweets_path, class: "button is-info ml-5 mt-5" %>

app/views/users/following.html.erb
<% @user_following.each do |user| %>
  <div class="columns is-mobile is-centered mt-5">
    <div class="column is-half">
      <div class="box">
        <div class="panel-block">
          <article class="media">
            <div class="media-left">
              <figure class="image is-32x32">
                <img src="https://bulma.io/images/placeholders/32x32.png">
              </figure>
            </div>
            <div class="media-content">
              <div class="content">
                <p>
                  <strong><%= link_to user.name, user_path(user.id) %></strong>
                  <small>@<%= user.username %></small>
                </p>
                <% if current_user %>
                  <%= render 'components/follow_btn', user: user %>
                <% end %>
              </div>
            </div>
          </article>
        </div>
      </div>
    </div>
  </div>
<% end %>

<%= render 'components/pagination', obj: @user_following %>

<%= link_to 'Back', tweets_path, class: "button is-info ml-5 mt-5" %>

app/views/users/show.html.erb
<div class="columns is-mobile is-centered mt-5">
  <div class="column is-half">
    <nav class="panel">
      <p class="panel-heading">Profile</p>
      <div class="panel-block">
        <article class="media">
          <div class="media-left">
            <figure class="image is-64x64">
              <%= gravatar_image_tag(@user.email, size: 64, alt: @user.name) %>
            </figure>
          </div>
          <div class="media-content">
            <div class="content">
              <p>
                <strong><%= @user.name %></strong> <br>
                <small>@<%= @user.username %></small>
              </p>
              <% if current_user.id == @user.id %>
                <%= link_to "Edit Profile", edit_user_registration_path, class: "button is-info" %>
              <% else %>
                <%= render 'components/follow_btn', user: @user %>
              <% end %>
            </div>
          </div>
        </article>
      </div>
      <div class="panel-block">
        <div class="level is-mobile">
          <div class="level-item has-centered-text">
            <div>
              <p class="heading">Tweets</p>
              <p class="title is-6"><%= @user.tweets.count %></p>
            </div>
          </div>
          <div class="level-item has-centered-text">
            <div>
              <p class="heading"><%= link_to "Followers", followers_path(@user.username) %></p>
              <p class="title is-6"><%= @user.followers.count %></p>
            </div>
          </div>
          <div class="level-item has-centered-text">
            <div>
              <p class="heading"><%= link_to "Following", following_path(@user.username) %></p>
              <p class="title is-6"><%= @user.following.count %></p>
            </div>
          </div>
        </div>
      </div>
    </nav>
  </div>
</div>

<%= render 'components/pagination', obj: @tweets %>

<% @tweets.each do |tweet| %>
  <div class="columns is-mobile is-centered mt-5">
    <div class="column is-half">
      <div class="box">
        <article class="media">
          <div class="media-left">
            <figure class="image is-64x64">
              <%= gravatar_image_tag(tweet.user.email, size: 64, alt: tweet.user.name) %>
            </figure>
          </div>
          <div class="media-content">
            <div class="content">
              <strong><%= tweet.user.name %></strong>
              <small>@<%= tweet.user.username %></small> -
              <small class="is-size-7"><%= tweet.created_at.getlocal.strftime("%d %b %y, %H:%M%p") %></small>
              <p> <%= tweet.tweet %> </p>
            </div>
            <% if user_signed_in? %>
            <nav class="level">
              <div class="level-left is-mobile">
                <%= link_to tweet, class: "level-item" do %>
                  <span class="icon"> <i class="fa fa-link" aria-hidden="true"></i> </span>
                <% end %>
                <%= link_to tweet, method: :delete, data: { confirm: "Are you sure?" } do %>
                  <span class="icon"> <i class="fa fa-trash-o" aria-hidden></i> </span>
                <% end %>
              </div>
            </nav>
          <% end %>
          </div>
        </article>
      </div>
    </div>
  </div>
<% end %>

<%= render 'components/pagination', obj: @tweets %>